"""Initial schema

Revision ID: 18d38310ca94
Revises: 
Create Date: 2025-11-25 00:13:59.077311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18d38310ca94'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('etl_log')
    op.drop_table('votacao_partido_munzona')
    op.drop_table('votacao_candidato_munzona')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votacao_candidato_munzona',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nr_turno', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ano_eleicao', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cd_eleicao', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dt_eleicao', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('sg_uf', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('sg_ue', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('nm_ue', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('cd_municipio', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nm_municipio', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('nr_zona', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('endereco_zona', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('bairro_zona', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('cep_zona', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('telefone_zona', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ds_cargo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('nr_candidato', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nm_candidato', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('nr_partido', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sg_partido', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('nm_partido', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('qt_votos_nominais', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qt_votos_nominais_validos', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('votacao_candidato_munzona_pkey')),
    sa.UniqueConstraint('ano_eleicao', 'nr_turno', 'sg_uf', 'cd_municipio', 'nr_zona', 'nr_candidato', name=op.f('uq_votacao_candidato'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('votacao_partido_munzona',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nr_turno', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ano_eleicao', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cd_eleicao', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ds_eleicao', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('dt_eleicao', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('sg_uf', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('sg_ue', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('nm_ue', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('cd_municipio', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nm_municipio', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('nr_zona', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('zona_eleitoral_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('endereco_zona', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('bairro_zona', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('cep_zona', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('telefone_zona', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cd_cargo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ds_cargo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('nr_partido', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sg_partido', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('nm_partido', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('qt_votos_nominais', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qt_votos_nominais_validos', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qt_votos_nominais_anulados', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('votacao_partido_munzona_pkey'))
    )
    op.create_table('etl_log',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('process_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('package_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('records_processed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('etl_log_pkey'))
    )
    # ### end Alembic commands ###
