"""add consulta_candidatos

Revision ID: 8d1b6bd14340
Revises: 
Create Date: 2025-12-05 11:47:57.639283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d1b6bd14340'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votacao_candidato_munzona')
    op.drop_index(op.f('ix_etl_log_process_name'), table_name='etl_log')
    op.drop_table('etl_log')
    op.drop_table('votacao_partido_munzona')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votacao_partido_munzona',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ano_eleicao', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nr_turno', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cd_eleicao', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ds_eleicao', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('dt_eleicao', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('sg_uf', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('sg_ue', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('nm_ue', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('cd_municipio', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nm_municipio', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('nr_zona', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cd_cargo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ds_cargo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('nr_partido', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sg_partido', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('nm_partido', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('qt_votos_legenda_validos', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qt_votos_nom_convr_leg_validos', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qt_total_votos_leg_validos', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qt_votos_nominais_validos', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qt_votos_legenda_anul_subjud', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qt_votos_nominais_anul_subjud', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qt_votos_legenda_anulados', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qt_votos_nominais_anulados', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('votacao_partido_munzona_pkey')),
    sa.UniqueConstraint('ano_eleicao', 'sg_uf', 'cd_municipio', 'nr_zona', 'nr_turno', 'nr_partido', 'cd_cargo', name=op.f('uq_votacao_partido'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('etl_log',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('process_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('records_processed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('etl_log_pkey'))
    )
    op.create_index(op.f('ix_etl_log_process_name'), 'etl_log', ['process_name'], unique=False)
    op.create_table('votacao_candidato_munzona',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ano_eleicao', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nr_turno', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cd_eleicao', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dt_eleicao', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('sg_uf', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('sg_ue', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('nm_ue', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('cd_municipio', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nm_municipio', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('nr_zona', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ds_cargo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('nr_candidato', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nm_candidato', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('nr_partido', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sg_partido', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('nm_partido', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('qt_votos_nominais', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qt_votos_nominais_validos', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('votacao_candidato_munzona_pkey')),
    sa.UniqueConstraint('ano_eleicao', 'nr_turno', 'sg_uf', 'cd_municipio', 'nr_zona', 'nr_candidato', name=op.f('uq_votacao_candidato'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
